#!/bin/bash

if [ "${1}" == "clean" ]; then
    rm -rf target
    rm -rf lib/target
else
    cd lib && cargo build --release && cd ..
    mkdir target
    clang++ src/main.cc -o target/math -L lib/target/release -lmath
fi
