[package]
name = "tally"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0"
dashmap = { version = "5.4", optional = true }
rayon = { version = "1.7", optional = true }

[features]
parallel = ["dashmap", "rayon"]
